behaviors:
  Jayden:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 4096 
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2e31
    time_horizon: 64
    summary_freq: 10000
engine_settings:
  time_scale: 1.0
  target_frame_rate: -1
  capture_frame_rate: 0