behaviors:
  Jayden:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e7
    time_horizon: 64
    summary_freq: 10000
  Player:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail: 
        strength: 0.5
        demo_path: "Demos/PlayerDemo_2.demo"
    behavioral_cloning:
      strength: 0.5
      demo_path: "Demos/PlayerDemo_2.demo"
    max_steps: 1e7
    time_horizon: 64
    summary_freq: 10000
engine_settings:
  time_scale: 1.0
  target_frame_rate: -1
  capture_frame_rate: 0